### ISSUE TITLE
Is kiwi irc down ? [Error] Refused to display 'https://kiwiirc.com/nextclient/?theme=sky#irc://irc.libera.chat/#testchann?nick=test_68975&encoding=utf8' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

### ISSUE THREAD

**Issue by atv2016** [KiwiChat/wp-kiwichat#4]
[Error] Refused to display 'https://kiwiirc.com/nextclient/?theme=sky#irc://irc.libera.chat/#testchan?nick=test_68975&encoding=utf8' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

It loads for a long time then timeout, and in addition I get above message. Some sort of CORS issue or just not available ?

**Comment by KiwiChat** [comment]
@atv2016 Kiwiirc is down and unavailable, you can use the [app-liberachat](urlhttps://wordpress.org/plugins/app-liberachat/) plugin https://wordpress.org/plugins/app-liberachat/

[https://app-libera.github.io/](https://app-libera.github.io)

**Comment by atv2016** [comment]
How is that plugin different, does it not also use liquid to load the nextclient js code?

or is it hosted locally, or maybe  on libera host?

**Comment by KiwiChat** [comment]
@atv2016 It is hosted on Liberachat, and only works on Liberachat. If you want to connect to another server, write to me and I will modify or make a plugin to your needs.

Regards 

[contact](https://contact.kiwichat.eu.org/)
